name: Deploy to Apache Server via SCP

on:
  push:
    branches:
      - main  # Trigger deployment when pushing to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2  # Checkout the repository

    - name: Install sshpass
      run: sudo apt-get install -y sshpass  # Install sshpass for password-based SSH/SCP authentication

    - name: Ensure the target directory exists on the server
      run: |
        # Ensure that the target directory exists on the server
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "mkdir -p /var/www/html/your-project"

    - name: Copy files to Apache server using SCP
      run: |
        # Copy project files to the Apache server using SCP
        sshpass -p ${{ secrets.SERVER_PASSWORD }} scp -r ./path/to/your/project/* ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}:/var/www/html/your-project/

    - name: Set permissions on Apache server
      run: |
        # Set file ownership to Apache user (www-data)
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "sudo chown -R www-data:www-data /var/www/html/your-project"
    
    - name: Restart Apache server
      run: |
        # Restart Apache to apply the changes
        sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "sudo systemctl restart apache2"
